import type { Metadata } from "next";
import { Inter, Lora, Rosarivo, Noto_Serif, Crimson_Text } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const rosarivo = Rosarivo({ weight: "400", subsets: ["latin"] });
const lora = Lora({ weight: "400", subsets: ["latin"] });
const notoSerif = Noto_Serif({ weight: "400", subsets: ["latin"] });
const crimsonText = Crimson_Text({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.className} relative`}>

        {children}
      </body>
    </html>
  );
}
